blog/article/urls.py
from os import name, pardir
from django.contrib import admin
from django.urls import path
from . import views 


app_name = 'article'


urlpatterns = [
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('addarticle/', views.addarticle, name = 'addarticle'),
    path('article/<int:id>', views.detail, name = 'detail'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('', views.articles, name = 'articles'),
    path('comment/<int:id>', views.addComment, name = 'comment'),

]

blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""blog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import include

from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('detail/<int:id>', views.detail, name = 'detail'),
    path('articles/', include('article.urls')),
    path('user/', include('user.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/article/models.py
from typing import Match
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models.base import Model

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Author')
    title = models.CharField(max_length=50, verbose_name='Title')
    content = RichTextField(verbose_name='Content')
    article_image = models.FileField(blank= True, null= True, verbose_name='Picture')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Created Date')

    # To show title name at articles page.
    def __str__(self):
        return self.title

    class Meta:
            ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name='Essay',related_name='comments')
    comment_author = models.CharField(max_length= 50, verbose_name= 'Name')
    comment_content = models.CharField(max_length=200, verbose_name='Comment')
    comment_date = models.DateTimeField(auto_now_add= True)
        

    def __str__(self):
        return self.comment_content


    class Meta:
        ordering = ['-comment_date']

blog/article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content','article_image']

blog/article/views.py
from .models import Article, Comment
from django.shortcuts import redirect, render, HttpResponse, get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):

    keyword = request.GET.get('keyword')
    
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request, 'articles.html', {'articles': articles})
    
    articles = Article.objects.all()
    return render(request, 'articles.html', {'articles': articles})
    

def index(request):
    contex = {
        'number1': 10,
        'number2':8,
    }
    return render(request, 'index.html', contex)


def about(request):
    return render(request, 'about.html')

def detail(request, id):
    return HttpResponse('detail: ' + str(id))
@login_required(login_url='user:login')
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        'articles': articles
    }
    return render(request, 'dashboard.html', context)
@login_required(login_url='user:login')
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.success(request, 'The Essay has been posted.')
        return redirect('index')

    return render(request, 'addarticle.html', {'form': form})


def detail(request, id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id = id)

    comments = article.comments.all()

    return render(request, 'detail.html', {'article': article, 'comments': comments})

@login_required(login_url='user:login')
def update(request, id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.success(request, 'The Essay has been updated.')
        return redirect('index')

    return render(request, 'update.html', {'form': form})

@login_required(login_url='user:login')
def delete(request, id):
    article = get_object_or_404(Article, id = id)
    article.delete()

    messages.success(request, 'Essay has been succesfully deleted.')
    return redirect('article:dashboard')


def addComment(request, id):
    article = get_object_or_404(Article, id = id)
    if request.method == 'POST':
        comment_author = request.POST.get('comment_author')
        comment_content = request.POST.get('comment_content')
        
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article

        newComment.save()

    return redirect(reverse('article:detail', kwargs = {'id' : id}))

blog/templates/about.html
{% extends 'layout.html' %}

{% block body %}
    <h3>About Us</h3>
    <hr>
    <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
         Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
         It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
         It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, 
         and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.


    </p>
{% endblock body %}

blog/templates/addarticle.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create an Essay</h3>
            <hr>

            <form method = 'POST' enctype="multipart/form-data">
                {%csrf_token%}
                {{form.media}}
                {{form | crispy}}
                <br>
                <button type="submit" class="btn btn-dark">Save</button>

            </form>
    </div>
</div>
    
{% endblock body %}

blog/templates/articles.html
{% extends 'layout.html' %}

{% block body %}
        <h3>Essays</h3>
        <hr>
        <div>
            <form >
                {% csrf_token %}
                <input type="text" name = 'keyword' class="input-sm">
                <button type="submit" class="btn btn-info">Search</button>

            </form>


        </div>
        
        {% if articles %}

            {% for article in  articles %}
        
            <div class="container mt-5">
                <div class="row">
                    <div class="col-lg-8">
                        
                        <!-- Post content-->
                        <article>
                            <!-- Post header-->
                            <header class="mb-4">
                                <!-- Post title-->  
                                <a href="{%url 'article:detail' article.id %}"><h1 class="fw-bolder mb-1">{{article.title}}</h1></a>  

                                <!-- Post meta content-->
                                <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author}}</div>
                                <!-- Post categories-->
                               
                            </header>
                            <!-- Preview image figure-->
                            {% if article.article_image %}
                                <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
             
                            {% endif %}
                            <!-- Post content-->
                            <section class="mb-5">
                                <p>{{article.content | safe | truncatechars:40}}</p>
                                <a href="{%url 'article:detail' article.id %}" class="btn btn-info" style="float: right;">To Continue</a>
                            </section>
                        </article>
                        <!-- Comments section-->
                        
                    </div>
                    <hr>
                    <!-- Side widgets-->
                    
                        <!-- Categories widget-->
                        
                        <!-- Side widget-->
                       
                    </div>
                </div>
            </div>
            <hr>
            
            {% endfor %}

            
        {% else %}
            <div class="alert alert-danger">There is no such an essay in this page.</div>            
        {% endif %}
     
{% endblock body %}

blog/templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}
<h3>Control Panel</h3>
<hr>
<p>Welcome, <small>{{request.user.username}}</small></p>
<hr>

<a class="btn btn-danger" href="/articles/addarticle">Add Essay</a>
<hr>


    
        {% if articles %}
        <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                        <th scope="col">Date</th>
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                    </tr>

                </thead>
                    <tbody>

        
            {% for article in articles %}
        
                <tr>
                    <th scope="row">{{article.id}}</th>
                    <td><a href="/articles/article/{{article.id}}">{{article.title}}</a></td>
                    <td>{{article.author}}</td>
                    <td>{{article.created_date}}</td>
                    <td><a href="/articles/update/{{article.id}}" class="btn btn-dark">Update</a></td>
                    <td><a href="/articles/delete/{{article.id}}" class="btn btn-danger">Delete</a></td>


                </tr> 
           

        {% endfor %}
        </tbody>
            </table>
        {% else %}
            <div class="alert alert-danger">There is no Essay</div>
        {% endif %}
        
   


{% endblock body %}

blog/templates/detail.html
{% extends 'layout.html' %}

{% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->  
                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author}}</div>
                    <!-- Post categories-->
                   
                </header>
                <!-- Preview image figure-->
                {% if article.article_image %}
                    <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..." /></figure>
 
                {% endif %}
                <!-- Post content-->
                <section class="mb-5">
                    <p>{{article.content | safe}}</p>
                </section>
            </article>
            <!-- Comments section-->
            {% if comments %}

            {% for comment in comments  %}
                <div class="d-flex">
                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                    <div class="ms-3">
                        <div class="fw-bold">{{comment.comment_author}}</div>
                        {{comment.comment_date}}<br>    
                        {{comment.comment_author}}
                    </div>
                </div>
                <hr>
            {% endfor %}
                
            {% else %}
                <div class="alert alert-danger">There is no comment, add first commment be first</div>
            {% endif %}
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form-->
                        <form class="mb-4" action="{% url 'article:comment' article.id %}" method="POST">
                            {%csrf_token%}
                            <input name="comment_author" class="form-control" type="text" placeholder="Name Please">
                            <textarea name='comment_content' class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea>
                            <button type="submit" name = 'comment' class="btn btn-danger">Send Comment</button>
                        </form>
                        <!-- Comment with nested comments-->
                        
                    </div>
                </div>
            </section>
            
        </div>
        <!-- Side widgets-->
        
            <!-- Categories widget-->
            
            <!-- Side widget-->
           
        </div>
    </div>
</div>
    
{% endblock body %}

blog/templates/index.html
{% extends 'layout.html' %}

{% block body %}
    <div class="jumbotron text-center" >
        <h3>Welcome To My Blog</h3>
        <p>We are gonna learn Django in that course.</p>
    </div>
    <p>
        {% if number1 == 7 %}
            <p>1. Sayımız 7'ye eşit</p>

        {% endif %}

    </p>

    <p>
        {% if request.user.is_authenticated %}
            Giriş yapılmış {{request.user.username}}
        {% else %}
            Giriş Yapılmamış
        {% endif %}

    </p>
{% endblock body %}

blog/templates/layout.html
<!DOCTYPE html>
{%load static%}}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <title>MyBlog</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <div class="container" style="margin-top: 100px; margin-bottom: 50px;">
        
            {% if messages %}
            
                {% for message in messages %}

                <div {% if message.tags %} class="alert alert-success {{ message.tags }}"{% endif %}>{{ message }} </div>
               
                {% endfor %}
            
            {% endif %} 
         
        {% block body %}

            
        {% endblock  %}

    </div>

    {% include 'includes/footer.html' %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->

</body>
</html>

blog/templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
            <hr>

            <form method = 'POST'>
                {%csrf_token%}
                {{form | crispy}}
                <br>
                <button type="submit" class="btn btn-dark">Login</button>

            </form>
    </div>
</div>
   
    
{% endblock body %}

blog/templates/register.html
{% extends 'layout.html' %}

{% block body %}
{%load crispy_forms_tags%}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Register</h3>
        <hr>
        <form method = "post">
            {% csrf_token%}
            {{form | crispy}}
            <button type="submit" class="btn btn-danger">Register</button>

        </form>
        <br>
    </div>
</div>
   
    
{% endblock body %}

blog/templates/update.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update an Essay</h3>
            <hr>

            <form method = 'POST' enctype="multipart/form-data">
                {%csrf_token%}
                {{form.media}}
                {{form | crispy}}
                <br>
                <button type="submit" class="btn btn-dark">Update Essay</button>

            </form>
    </div>
</div>
    
{% endblock body %}